/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProjectRouteImport } from "./routes/$project"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProjectIndexRouteImport } from "./routes/$project/index"
import { Route as ProjectSplatRouteImport } from "./routes/$project/$"

const ProjectRoute = ProjectRouteImport.update({
  id: "/$project",
  path: "/$project",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectSplatRoute = ProjectSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => ProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$project": typeof ProjectRouteWithChildren
  "/$project/$": typeof ProjectSplatRoute
  "/$project/": typeof ProjectIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$project/$": typeof ProjectSplatRoute
  "/$project": typeof ProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$project": typeof ProjectRouteWithChildren
  "/$project/$": typeof ProjectSplatRoute
  "/$project/": typeof ProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/$project" | "/$project/$" | "/$project/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$project/$" | "/$project"
  id: "__root__" | "/" | "/$project" | "/$project/$" | "/$project/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRoute: typeof ProjectRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$project": {
      id: "/$project"
      path: "/$project"
      fullPath: "/$project"
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$project/": {
      id: "/$project/"
      path: "/"
      fullPath: "/$project/"
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    "/$project/$": {
      id: "/$project/$"
      path: "/$"
      fullPath: "/$project/$"
      preLoaderRoute: typeof ProjectSplatRouteImport
      parentRoute: typeof ProjectRoute
    }
  }
}

interface ProjectRouteChildren {
  ProjectSplatRoute: typeof ProjectSplatRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectSplatRoute: ProjectSplatRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRoute: ProjectRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
