{{- if .Values.buntime.masterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buntime.fullname" . }}
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
type: Opaque
stringData:
  RUNTIME_MASTER_KEY: {{ .Values.buntime.masterKey | quote }}
{{- end }}
