{{- if or .Values.buntime.masterKey .Values.buntime.libsqlAuthToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buntime.fullname" . }}
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.buntime.masterKey }}
  RUNTIME_MASTER_KEY: {{ .Values.buntime.masterKey | quote }}
  {{- end }}
  {{- if .Values.buntime.libsqlAuthToken }}
  LIBSQL_AUTH_TOKEN: {{ .Values.buntime.libsqlAuthToken | quote }}
  {{- end }}
{{- end }}
