/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as DashboardIndexRouteImport } from "./routes/_dashboard/index"
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects.$projectId"

const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/projects/$projectId": typeof ProjectsProjectIdRoute
  "/": typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  "/projects/$projectId": typeof ProjectsProjectIdRoute
  "/": typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_dashboard": typeof DashboardRouteWithChildren
  "/projects/$projectId": typeof ProjectsProjectIdRoute
  "/_dashboard/": typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/projects/$projectId" | "/"
  fileRoutesByTo: FileRoutesByTo
  to: "/projects/$projectId" | "/"
  id: "__root__" | "/_dashboard" | "/projects/$projectId" | "/_dashboard/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/": {
      id: "/_dashboard/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/projects/$projectId": {
      id: "/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
