/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WatchRouteImport } from "./routes/watch"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as QueueRouteImport } from "./routes/queue"
import { Route as MetricsRouteImport } from "./routes/metrics"
import { Route as EntriesRouteImport } from "./routes/entries"
import { Route as AtomicRouteImport } from "./routes/atomic"
import { Route as IndexRouteImport } from "./routes/index"

const WatchRoute = WatchRouteImport.update({
  id: "/watch",
  path: "/watch",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: "/queue",
  path: "/queue",
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: "/metrics",
  path: "/metrics",
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: "/entries",
  path: "/entries",
  getParentRoute: () => rootRouteImport,
} as any)
const AtomicRoute = AtomicRouteImport.update({
  id: "/atomic",
  path: "/atomic",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/atomic": typeof AtomicRoute
  "/entries": typeof EntriesRoute
  "/metrics": typeof MetricsRoute
  "/queue": typeof QueueRoute
  "/search": typeof SearchRoute
  "/watch": typeof WatchRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/atomic": typeof AtomicRoute
  "/entries": typeof EntriesRoute
  "/metrics": typeof MetricsRoute
  "/queue": typeof QueueRoute
  "/search": typeof SearchRoute
  "/watch": typeof WatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/atomic": typeof AtomicRoute
  "/entries": typeof EntriesRoute
  "/metrics": typeof MetricsRoute
  "/queue": typeof QueueRoute
  "/search": typeof SearchRoute
  "/watch": typeof WatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/atomic"
    | "/entries"
    | "/metrics"
    | "/queue"
    | "/search"
    | "/watch"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/atomic"
    | "/entries"
    | "/metrics"
    | "/queue"
    | "/search"
    | "/watch"
  id:
    | "__root__"
    | "/"
    | "/atomic"
    | "/entries"
    | "/metrics"
    | "/queue"
    | "/search"
    | "/watch"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtomicRoute: typeof AtomicRoute
  EntriesRoute: typeof EntriesRoute
  MetricsRoute: typeof MetricsRoute
  QueueRoute: typeof QueueRoute
  SearchRoute: typeof SearchRoute
  WatchRoute: typeof WatchRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/watch": {
      id: "/watch"
      path: "/watch"
      fullPath: "/watch"
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/queue": {
      id: "/queue"
      path: "/queue"
      fullPath: "/queue"
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/metrics": {
      id: "/metrics"
      path: "/metrics"
      fullPath: "/metrics"
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/entries": {
      id: "/entries"
      path: "/entries"
      fullPath: "/entries"
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/atomic": {
      id: "/atomic"
      path: "/atomic"
      fullPath: "/atomic"
      preLoaderRoute: typeof AtomicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtomicRoute: AtomicRoute,
  EntriesRoute: EntriesRoute,
  MetricsRoute: MetricsRoute,
  QueueRoute: QueueRoute,
  SearchRoute: SearchRoute,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
