/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as RedirectsIndexRouteImport } from "./routes/redirects/index"
import { Route as DeploymentsIndexRouteImport } from "./routes/deployments/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectsIndexRoute = RedirectsIndexRouteImport.update({
  id: "/redirects/",
  path: "/redirects/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: "/deployments/",
  path: "/deployments/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/deployments": typeof DeploymentsIndexRoute
  "/redirects": typeof RedirectsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/deployments": typeof DeploymentsIndexRoute
  "/redirects": typeof RedirectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/deployments/": typeof DeploymentsIndexRoute
  "/redirects/": typeof RedirectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/deployments" | "/redirects"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/deployments" | "/redirects"
  id: "__root__" | "/" | "/deployments/" | "/redirects/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  RedirectsIndexRoute: typeof RedirectsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/redirects/": {
      id: "/redirects/"
      path: "/redirects"
      fullPath: "/redirects"
      preLoaderRoute: typeof RedirectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deployments/": {
      id: "/deployments/"
      path: "/deployments"
      fullPath: "/deployments"
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  RedirectsIndexRoute: RedirectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
