/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WatchIndexRouteImport } from "./routes/watch/index"
import { Route as SearchIndexRouteImport } from "./routes/search/index"
import { Route as QueueIndexRouteImport } from "./routes/queue/index"
import { Route as MetricsIndexRouteImport } from "./routes/metrics/index"
import { Route as KeysIndexRouteImport } from "./routes/keys/index"
import { Route as AtomicIndexRouteImport } from "./routes/atomic/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: "/watch/",
  path: "/watch/",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: "/search/",
  path: "/search/",
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: "/queue/",
  path: "/queue/",
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: "/metrics/",
  path: "/metrics/",
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: "/keys/",
  path: "/keys/",
  getParentRoute: () => rootRouteImport,
} as any)
const AtomicIndexRoute = AtomicIndexRouteImport.update({
  id: "/atomic/",
  path: "/atomic/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/atomic": typeof AtomicIndexRoute
  "/keys": typeof KeysIndexRoute
  "/metrics": typeof MetricsIndexRoute
  "/queue": typeof QueueIndexRoute
  "/search": typeof SearchIndexRoute
  "/watch": typeof WatchIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/atomic": typeof AtomicIndexRoute
  "/keys": typeof KeysIndexRoute
  "/metrics": typeof MetricsIndexRoute
  "/queue": typeof QueueIndexRoute
  "/search": typeof SearchIndexRoute
  "/watch": typeof WatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/atomic/": typeof AtomicIndexRoute
  "/keys/": typeof KeysIndexRoute
  "/metrics/": typeof MetricsIndexRoute
  "/queue/": typeof QueueIndexRoute
  "/search/": typeof SearchIndexRoute
  "/watch/": typeof WatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/atomic"
    | "/keys"
    | "/metrics"
    | "/queue"
    | "/search"
    | "/watch"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/atomic" | "/keys" | "/metrics" | "/queue" | "/search" | "/watch"
  id:
    | "__root__"
    | "/"
    | "/atomic/"
    | "/keys/"
    | "/metrics/"
    | "/queue/"
    | "/search/"
    | "/watch/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtomicIndexRoute: typeof AtomicIndexRoute
  KeysIndexRoute: typeof KeysIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/watch/": {
      id: "/watch/"
      path: "/watch"
      fullPath: "/watch"
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search/": {
      id: "/search/"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/queue/": {
      id: "/queue/"
      path: "/queue"
      fullPath: "/queue"
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/metrics/": {
      id: "/metrics/"
      path: "/metrics"
      fullPath: "/metrics"
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/keys/": {
      id: "/keys/"
      path: "/keys"
      fullPath: "/keys"
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/atomic/": {
      id: "/atomic/"
      path: "/atomic"
      fullPath: "/atomic"
      preLoaderRoute: typeof AtomicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtomicIndexRoute: AtomicIndexRoute,
  KeysIndexRoute: KeysIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
